Ammo.btCollisionObject.CollisionFlags =
  StaticObject: 1
  KinematicObject: 2
  NoContactResponse: 4
  CustomMaterialCallback: 8
  CharacterObject: 16
  DisableVisualizeObject: 32
  DisableSPUCollisionProcessing: 64
  HasContactStiffnessDamping: 128
  HasCustomDebugRenderingColor: 256
  HasFrictionAnchor: 512
  HasCollisionSoundsTrigger: 1024
